console.log("Hello world!")
console.log("You can change the word")
console.log("the things are happen")
console.log("Greate job!")
console.log("the things are happen here too")
console.log("i belive in your potential")
